# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGMyMzYxMjMwZTM0MDgxOGQ3ZmJjNmEzZmJkOTA0MWViZDNlZmQ3ODhlNDQ1ZWRhMGEzZmYyYmFlZTNjZWNhYjQ3ZDQ4MmEzMDcwMDBhYjA2OGYzZDlmNDY2YThmZjY5MWU1OTViODZlZDIxOGRhYzJmMzdmYWQwNGQ4NjQxZTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
